### ISSUE TITLE
mongo-connector stop working if a document contains invalid data  when dumping collections

### ISSUE THREAD

**Issue by Jinshui** [mongodb-labs/mongo-connector#334] opened 2015-10-09 08:41 UTC
While dumping a collection from mongodb to elasticsearch, the mongo-connector exit because one of the document has an invalid date value. The following is the error trace:

>2015-10-09 15:46:35,840 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 110, in streaming_bulk
    for action, data in chunk:
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
    for doc in docs:
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 442, in docs_to_dump
    for doc in cursor:
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1039, in _refresh
    limit, self.__id))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 958, in __send_message
    self.__compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 121, in _unpack_response
    compile_re)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 537, in decode_all
    tz_aware, uuid_subtype, compile_re))
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 331, in _elements_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 320, in _element_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 234, in _get_date
    dt = EPOCH_NAIVE + datetime.timedelta(seconds=seconds)
InvalidBSON: date value out of range
2015-10-09 15:46:35,841 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient('localhost', 27017), u'local'), u'oplog.rs')
2015-10-09 15:46:35,841 [DEBUG] mongo_connector.oplog_manager:167 - OplogThread: Last entry is the one we already processed.  Up to date.  Sleeping.
2015-10-09 15:46:36,597 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140718959515392)> unexpectedly stopped! Shutting down
2015-10-09 15:46:36,598 [INFO] mongo_connector.connector:359 - MongoConnector: Stopping all OplogThreads
>2015-10-09 15:46:36,598 [DEBUG] mongo_connector.oplog_manager:330 - OplogThread: exiting due to join call.

I think the process should never exit if one of the docs fails to be dumped, instead, it should log the error for the doc and then continue to dump next doc in the cursor.

**Comment by marcinkubica** [comment] 2015-10-09 11:43
Had this too. 'Continue in error' doesn't help here.

**Comment by Sebmaster** [comment] 2015-10-09 13:32
Same issue as in #279.

**Comment by Jinshui** [comment] 2015-10-09 15:18
Thanks Sebmaster. Yes, the issue is exactly the same as your comments in #279. In my case, there is a date field having the year like yyyyy.

>"originalAirDate" : ISODate("20131-07-10T00:00:00Z")

This causes the pymongo to fail to parse the date, and raise the error to mongo-connector, and then mongo-connector exit. 

I think mongo-connector should not exit in cases like this, it should log error for this doc and continue to dump next doc.

**Comment by behackett** [comment] 2015-10-13 21:49
I'm closing this issue as a duplicate of #279. I've added a comment to that ticket explaining what causes this issue and a potential workaround.

**Closed by behackett** 2015-10-13 21:49 UTC
