### ISSUE TITLE
Elastic 5 support

### ISSUE THREAD

**Issue by villasv** [mongodb-labs/mongo-connector#559] opened 2016-10-24 15:11 UTC
What is the current status of elasticsearch 5 compatibility? Has anyone tested?

**Comment by ShaneHarvey** [comment] 2016-10-24 23:18
So I just tested the elasticsearch-py 5.0.0, elastic2-doc-manager master, and elasticsearch server version 2.2.0 and the tests pass which you can see here: https://travis-ci.org/ShaneHarvey/elastic2-doc-manager/builds/170212353.

elasticsearch-py 5.0.0, elastic2-doc-manager master, and elasticsearch server version 5.0.0-rc1 also pass the tests after a trivial change to replace a `filtered` query with `bool` : https://travis-ci.org/ShaneHarvey/elastic2-doc-manager/builds/170269350 

The other way does not work. elasticsearch-py 2.4.0, elastic2-doc-manager master, and elasticsearch server version 5.0.0-rc1 fails which you can see here: https://travis-ci.org/ShaneHarvey/elastic2-doc-manager/builds/170255998

I opened https://github.com/mongodb-labs/elastic2-doc-manager/pull/24 for elastic 2.X and 5.0.0 compatibility. After that is merged in you can try using mongo-connector/elastic2-doc-manager with Elastic 5 by upgrading elasticsearch-py manually:
```
$ pip install mongo-connector
$ pip install https://github.com/mongodb-labs/elastic2-doc-manager/archive/master.zip
$ pip install --upgrade elasticsearch-py==5.0.0
$ # run mongo-connector with an elasticsearch 5.0.0 target
```

**Comment by ShaneHarvey** [comment] 2016-10-25 17:28
Closing this as a duplicate of #453.

**Closed by ShaneHarvey** 2016-10-25 17:28 UTC
Labels: duplicate, question
