### ISSUE TITLE
Solr: ISODate is not stored.

### ISSUE THREAD

**Issue by atuljangra** [mongodb-labs/mongo-connector#376] opened 2016-01-19 01:53 UTC
I've a mongodb, solr and mongo-connector setup that was working fine.
Then I decided to store date in my collection:
"published_date" : ISODate("2016-01-19T00:16:05Z")
This is being stored in the mongodb. And I've the following line in my schema.xml:
   <field name="published_date" type="date" indexed="true" stored="true" />
Where "date" is a general 
 <fieldType name="date" class="solr.TrieDateField" precisionStep="0" positionIncrementGap="0"/>
as stated in https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/doc_managers/schema.xml

Now the problem is that in the documents, only some of the documents seem to have the published_date field. Log file also doesn't show any errors. The documents are present, but they don't have this field.

**Comment by llvtt** [comment] 2016-01-20 20:13
I'm not sure that I understand what the issue is. Did you add `published_date` to every document in the collection, but only some of the documents are showing `published_date` in Solr? Could it be changes haven't been committed to Solr in some time, and Solr isn't showing the latest indexed documents?

**Comment by atuljangra** [comment] 2016-01-21 00:55
Yes. It seems that the changes are taking very very long time to show in the all of the solr documents.
I have around 40K documents and it is still indexing solr. After 2 days. Total operations is around 3 per document. Is it okay for the connector to take this much time?

We can close this one now.

**Comment by llvtt** [comment] 2016-01-21 18:15
That's unusually slow for mongo-connector, but it's very possible that there's something else going on that's taking up Solr's resources. I unfortunately don't have much insight into general Solr performance issues, but you might have some luck asking on the Solr mailing list here: https://lucene.apache.org/solr/resources.html#solr-user-list-solr-userlucene

**Closed by llvtt** 2016-01-21 18:15 UTC

**Comment by atuljangra** [comment] 2016-01-30 18:43
Thank you! Anyway it took hell lot of time, but it works! So far so good.

**Comment by behackett** [comment] 2016-01-30 19:27
Can you share the solution to your problem? It might help other users in the future.

**Comment by atuljangra** [comment] 2016-01-30 19:46
Actually there is no solution.
All the documents did get updated at last. But it was really slow. Now I've the ISODate in all my documents.
