### ISSUE TITLE
Skipping oplog entry: '<db_name>.tmp.agg_out.1' is not in the namespace configuration.

### ISSUE THREAD

**Issue by thephysicsriot** [mongodb-labs/mongo-connector#695] opened 2017-04-10 19:25 UTC
Wanted to report an issue and give my fix.

I have a collection that I am trying to dump into Elasticsearch while renaming it so that the db collection name is used for the ES index name and type. However, I got the following log message (10s of thousands of times):

`2017-04-10 14:56:43,809 [DEBUG] mongo_connector.oplog_manager:175 - OplogThread: Skipping oplog entry: 'production.tmp.agg_out.1' is not in the namespace configuration.`

Here is my config file with the desired `namespaces` handling

    {
    "mainAddress": "db-address.7495.mongodbdns.com:27000",
    "oplogFile": "oplog.timestamp",
    "noDump": true,
    "batchSize": -1,
    "verbosity": 3,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "mongo-connector.log"
    },

    "authentication": {
        "adminUsername": "app-admin",
        "passwordFile": "mongo-connector.pwd"
    },

    "namespaces": {
        "production.test": {
            "rename" : "tests.test"
        }
    },

    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "127.0.0.1:9200",
            "bulkSize": 5000
        }
    ]
    }

After some digging I found that producing a collection from the mongodb aggregation `$out` stage makes temp collections named like `db_name.tmp.agg_out.n`. I did in fact produce the `test` collection from an aggregation with `$out`. I figured the quickest thing to do was to drop the `tmp.agg_out.n` collection, but I couldn't find it!

Instead I did `db.repairDatabase()` and ran mongo-connector again, which worked without issue.

**Comment by ShaneHarvey** [comment] 2017-04-10 20:03
You are correct that an aggregation with `$out` produces a temporary collection `db_name.tmp.agg_out.n`. The temporary collection is used to gather the results of the aggregation. Once complete, the temporary collection is renamed using the `renameCollection` command to the collection name specified by the `$out`. 

Right now mongo-connector does not have any special handling of temp collections so it will not include `production. tmp.agg_out.1` when you specified to only include `production.test`. If you want to filter and rename all collections in `production` you can use:
```
"namespaces": {
    "production.*": {
        "rename" : "tests.*"
    }
},
```

**Comment by thephysicsriot** [comment] 2017-04-10 20:29
Hmm then that means I didn't correctly diagnose what is happening to me. It appears that toggling `noDump` between true and false is causing this issue. On another db, where I have not used `$out` for any of the collections, I am getting the same message but with a regular collection (meaning not a tmp one).

`OplogThread: Skipping oplog entry: 'production.imp' is not in the namespace configuration.`

It is in fact not in the namespace configuration because I don't want to do anything with the `imp` collection. Thoughts?

**Comment by ShaneHarvey** [comment] 2017-04-10 20:33
`OplogThread: Skipping oplog entry: 'production.imp' is not in the namespace configuration.`
This is simply a debug log entry to indicate why we are not applying the given oplog entry. Changes to `production.imp` are being correctly ignored because the namespace configuration does not include it.

**Comment by thephysicsriot** [comment] 2017-04-10 20:47
I see. Let me outline what my actual problem is. 

When I use `noDump: false`, the documents dump in a matter of seconds, I get an oplog.timestamp file, and it tails the oplog indefinitely with heartbeat messages. When I use `noDump: true` (so that I can get a timestamp file alone, I don't care about dumping atm), it logs all these "skipping" messages of which there are 100s of millions because the `imps` coll is huge. 

That is why I am confused here, `noDump: false` seems to be getting right to the point and dumping the target collection and `noDump: true` is running over and skipping a bunch of oplog entries. While I haven't yet waited more than a few minutes, using `noDump: true` is taking significantly longer when my expectation, though I am naive to the internals, is that it would take less time. 

Am I understanding the purpose of `noDump`?

**Comment by ShaneHarvey** [comment] 2017-04-10 21:10
[noDump](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#nodump) causes mongo-connector to start tailing the oplog from the *oldest* entry. This might be changed to the *newest* entry in a future release.

I'm going to close this as a duplicate of https://github.com/mongodb-labs/mongo-connector/issues/586 and https://github.com/mongodb-labs/mongo-connector/issues/305.

**Closed by ShaneHarvey** 2017-04-10 21:10 UTC
