### ISSUE TITLE
-n option in mongo-connector does not work when collection name contains _ (underscore)

### ISSUE THREAD

**Issue by adeelahmadch** [mongodb-labs/mongo-connector#441] opened 2016-05-03 11:39 UTC
**OS: Amazon Linux
PIP: pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)
Mongo-Connector: mongo-connector-2.3**

**Description: **I am trying to sync data between MongoDB 3.2.4 and Elastic Search using mongo-connector. however when i run;

**# mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager -n dbname.abc_elements**

 it  does not throw any error neither it adds data in Elastic Search. if i change my collection name by removing _ (underscore) it works just fine. 

According to this https://docs.mongodb.org/manual/reference/limits/#naming-restrictions i can use _ and it is not a restricted character.

**Comment by sliwinski-milosz** [comment] 2016-05-09 14:26
I think that the problem is that Elasticsearch do not accept mapping names with undescores.

Because of that I added mapping to my namespace:
https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#namespacesmapping

In my configuration file it looks like:
    "namespaces": {
        "include": ["test._User"],
        "mapping": {
            "test._User": "test.User"
        }
    },

Works fine for me.

**Comment by aherlihy** [comment] 2016-05-09 18:09
@adeelahmadch, do you collection names start with an underscore or are they "abc_elements"? 

@sliwinski-milosz is correct that Elastic does not accept mapping names starting with underscores, but I just tested with MongoDB 3.2.4, Mongo-Connector 2.3, and Elastic 2.2.0 with collection="abc_elements" and it seems to be working fine. What version of elastic are you using? Did you see any errors in the Elastic logs, or the mongo-connector.log file?

**Comment by jaredkipe** [comment] 2016-05-25 21:40
I _debug-senses_ tell me this might be related to this one https://github.com/mongodb-labs/mongo-connector/issues/310
Try updating each collection you are trying to dump at least once -recently- before trying to mongo-connector it.

**Comment by llvtt** [comment] 2016-07-18 21:01
@adeelahmadch, have you had any success with the advice of @sliwinski-milosz or @jaredkipe? May I close this issue now? Note: I've added #310 to the 2.4.1 milestone, so any temporary fix that involves creating a dummy document just to create the namespace will be unnecessary in the next release.

**Comment by adeelahmadch** [comment] 2016-07-19 10:48
Sorry guys for replying late on this. First of all thank you for looking into this. i found a work around for my issue not sure why that happened. 

**Command that was not working.** 
mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager -n dbname.abc_elements

i was able to fix this issue by passing _name in command separated format.

**Command that worked.** 
mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager -n dbname.abc_elements,dbname.testcollection
 

OS: Amazon Linux
PIP: pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)
Mongo-Connector: mongo-connector-2.3
Elastic Search Version: 2.3.1
MongoDB Version: 3.2.4


@llvtt You can close this issue.

**Closed** 2016-07-19 18:18 UTC
