### ISSUE TITLE
How to make mongo-connector highly available in production

### ISSUE THREAD

**Issue by sopnopriyo** [mongodb-labs/mongo-connector#546] opened 2016-10-07 03:33 UTC
Mongo-connector might go down due to a lot of issues. If one instance is down other should continue to run , that's the traditional practice. 
So, in case of mongo-connector, how can we ensure high availability ?

Thanks,
Shahin 
Cloud Application developer
Hilti

**Comment by gsvarovsky** [comment] 2016-10-24 08:10
#275 has some discussion of this topic

**Comment by ShaneHarvey** [comment] 2016-10-28 22:20
Closing as a duplicate of #275

**Closed by ShaneHarvey** 2016-10-28 22:20 UTC
Labels: duplicate
