### ISSUE TITLE
get "mongo_connector.util:87 - Fatal Exception" in mongo connector 

### ISSUE THREAD

**Issue by licett** [mongodb-labs/mongo-connector#315] opened 2015-09-02 02:35 UTC
hi ,
I get error "mongo_connector.util:87 - Fatal Exception" about every several hours when I start it with command "mongo-connector -m x.x.x.x:xx -t http://10.117.51.x:8983/solr/madao_shard1_replica2 -d solr_doc_manager --unique-key=id --auto-commit-interval=0 --verbose"

And the log from mongo connector is as following (last part of the log):
'http://10.117.51.84:8983/solr/madao_shard1_replica2/update/?commit=true' (post) with body 'u'<add com' in 0.108 seconds.
2015-09-01 22:26:06,102 [DEBUG] mongo_connector.oplog_manager:289 - OplogThread: Doc is processed.
2015-09-01 22:26:06,102 [DEBUG] mongo_connector.oplog_manager:189 - OplogThread: Iterating through cursor, document number in this cursor is 97
2015-09-01 22:26:06,102 [DEBUG] mongo_connector.oplog_manager:234 - OplogThread: Operation for this entry is i
2015-09-01 22:26:06,102 [DEBUG] pysolr:797 - Starting to build add request...
2015-09-01 22:26:06,103 [DEBUG] pysolr:812 - Built add request of 1 docs in 0.00 seconds.
2015-09-01 22:26:06,103 [DEBUG] pysolr:291 - Starting request to 'http://10.117.51.84:8983/solr/madao_shard1_replica2/update/?commit=true' (post) with body 'u'<add com'...
2015-09-01 22:26:06,222 [DEBUG] requests.packages.urllib3.connectionpool:383 - "POST /solr/madao_shard1_replica2/update/?commit=true HTTP/1.1" 200 None
2015-09-01 22:26:06,223 [INFO] pysolr:325 - Finished 'http://10.117.51.84:8983/solr/madao_shard1_replica2/update/?commit=true' (post) with body 'u'<add com' in 0.120 seconds.
2015-09-01 22:26:06,224 [DEBUG] mongo_connector.oplog_manager:289 - OplogThread: Doc is processed.
2015-09-01 22:26:06,224 [DEBUG] mongo_connector.oplog_manager:189 - OplogThread: Iterating through cursor, document number in this cursor is 98
2015-09-01 22:26:06,224 [DEBUG] mongo_connector.oplog_manager:234 - OplogThread: Operation for this entry is u
2015-09-01 22:26:06,224 [DEBUG] pysolr:291 - Starting request to 'http://10.117.51.84:8983/solr/madao_shard1_replica2/update/?commit=true' (post) with body 'u'<commit '...
2015-09-01 22:26:06,232 [DEBUG] requests.packages.urllib3.connectionpool:383 - "POST /solr/madao_shard1_replica2/update/?commit=true HTTP/1.1" 200 None
2015-09-01 22:26:06,233 [INFO] pysolr:325 - Finished 'http://10.117.51.84:8983/solr/madao_shard1_replica2/update/?commit=true' (post) with body 'u'<commit ' in 0.008 seconds.
2015-09-01 22:26:06,233 [DEBUG] pysolr:291 - Starting request to 'http://10.117.51.84:8983/solr/madao_shard1_replica2/select/?q=id%3A5010&wt=json' (get) with body ''...
2015-09-01 22:26:06,239 [DEBUG] requests.packages.urllib3.connectionpool:383 - "GET /solr/madao_shard1_replica2/select/?q=id%3A5010&wt=json HTTP/1.1" 200 None
2015-09-01 22:26:06,240 [INFO] pysolr:325 - Finished 'http://10.117.51.84:8983/solr/madao_shard1_replica2/select/?q=id%3A5010&wt=json' (get) with body '' in 0.006 seconds.
2015-09-01 22:26:06,241 [DEBUG] pysolr:659 - Found '4' search results.
2015-09-01 22:26:06,241 [ERROR] mongo_connector.util:87 - Fatal Exception

oh, forget to say that I use pip to upgrade mongo-connector yesterday.

**Comment by llvtt** [comment] 2015-09-02 15:37
Was there any other output from mongo-connector when it exited?

**Comment by licett** [comment] 2015-09-06 02:14
hi llvtt, I get a error message from stdout:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 263, in run
    ns, timestamp)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 246, in update
    doc.pop('ns')
KeyError: 'ns'

Logging to mongo-connector.log.

I check my schema.xml, and sure that I define this field : 
<field name="ns" type="string" indexed="true" stored="true"/>

So, any suggestion?

**Comment by licett** [comment] 2015-09-06 05:44
I am afraid that error " KeyError: 'ns' " and error "mongo_connector.util:87 - Fatal Exception" is not the same.
Because I got  ns error once , however "mongo_connector.util:87 - Fatal Exception" 4 times.

As you update the project , I will try the latest code and report it later.

**Comment by licett** [comment] 2015-09-08 12:37
I got it!
There are two data source of my solr collection. 
One is mongo , it is all right. And the other is mysql, though data from that is only  a small part.
So it raise a exception when mongo connector update a record which has no member named "ns".
I add try and except to solve this problem(I think check the record so make sure it is a mongo record is a better way).

**Comment by llvtt** [comment] 2015-09-15 19:30
I'm glad you got it working! It's a little surprising that there was this collision between MySQL and MongoDB, because mongo-connector applies updates to documents it retrieves by `id`. It sounds like was a document in MySQL that had the same `id` as one in MongoDB. Does that sound plausible?

**Comment by aherlihy** [comment] 2016-02-22 16:13
@licett I'm going to close this issue because you got it working, but if it comes up again please feel free to file a new issue or re-open this one. Thank you!

**Closed by aherlihy** 2016-02-22 16:13 UTC

**Comment by parakhod** [comment] 2016-03-03 19:42
Got the same error, mongo-connector crashes every 3-4 days.
[ERROR] mongo_connector.util:87 - Fatal Exception.

Mongodb / elasticsearch.

Also in stdout log i have similar error message (the first part looks exactly the same), except the reason:

`  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 99, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10))`
