### ISSUE TITLE
pymongo 3.x support

### ISSUE THREAD

**Issue by haizi-zh** [mongodb-labs/mongo-connector#385] opened 2016-02-04 04:37 UTC
pymongo 3.x changes some of its APIs. For example, the signature of `collection.find` has changed significantly ([see here](http://api.mongodb.org/python/current/api/pymongo/collection.html#pymongo.collection.Collection.find)), which will break mongo-connector:

> Changed in version 3.0: Changed the parameter names spec, fields, timeout, and partial to filter, projection, no_cursor_timeout, and allow_partial_results respectively. Added the cursor_type, oplog_replay, and modifiers options. Removed the network_timeout, read_preference, tag_sets, secondary_acceptable_latency_ms, max_scan, snapshot, tailable, await_data, exhaust, as_class, and slave_okay parameters. Removed compile_re option: PyMongo now always represents BSON regular expressions as Regex objects. Use try_compile() to attempt to convert from a BSON regular expression to a Python regular expression object. Soft deprecated the manipulate option.

I've noticed that the master branch relies on pymongo 2.7. I wish it be compatible with pymongo 3.X in near future.

**Comment by behackett** [comment] 2016-02-04 04:52
This is a duplicate of #306. The changes for this are currently in code review.

**Closed by behackett** 2016-02-04 04:52 UTC
