### ISSUE TITLE
Ability to filter documents based on field value

### ISSUE THREAD

**Issue by geecko86** [mongodb-labs/mongo-connector#588] opened 2016-11-15 02:51 UTC
I don't know if this should be a question or a feature request but I couldn't find how to do this.

The idea is to be able to filter which documents should be sent based on their content.
I.e. if a document has a certain field set to false, then it shouldn't be sent to a target.

Other possibility: only send documents for which a specified field exists or doesn't exist.

**Comment by ShaneHarvey** [comment] 2016-11-16 22:59
Closing as duplicate of https://github.com/mongodb-labs/mongo-connector/issues/304.

**Closed by ShaneHarvey** 2016-11-16 22:59 UTC
