### ISSUE TITLE
Failed during dump collection and unavailable_shards_exception

### ISSUE THREAD

**Issue by BlueRayONE** [mongodb-labs/mongo-connector#633] opened 2017-01-24 11:07 UTC
As already mentioned in https://github.com/mongodb-labs/mongo-connector/issues/552#issuecomment-273766279 I'm experiencing an "Exception during collection dump" because of a "ConnectionTimeout caused by ReadTimeoutError" (see logs and other details in linked comment).
I'm opening a new issue now, because a new circumstance appreared.
In the meantime, on some new tries to do a resync, I get a new error. Again an "Exception during collection dump" with the same Traceback, but at the end another reason.
```
OperationFailed: (u'611 document(s) failed to index.', [])
```
The array contains (I think 611) elements of the following form:
```
{u'index': {u'status': 503, u'_type': u'dbXY', u'_id': u'xyz', 
  u'error':  {u'reason': u'[indexAB][3] primary shard is not active Timeout: [1m], request: 
    [BulkShardRequest to [indexAB] containing [314] requests]', 
    u'type': u'unavailable_shards_exception'},
  u'_index': u'indexAB'}}
```
I double checked it, ElasticSearch is running. 
Some time before I had played around with the BulkSize and set it to 3000. Because of the 'unavailable_shards_exception" I hoped to have found the reason and reset it to 1000. No improvement. 
Sometimes the connector is stopped by the ReadTimeoutError, sometimes by the OperationFailed error, I can't detect a pattern when which error appears. I don't even know if these errors have the same source or if there are multiple problems...everything came with update to v2.5.0.

Any ideas on this problem(s)?

**Comment by ShaneHarvey** [comment] 2017-01-24 20:45
The problem is that the Elasticsearch doc managers do not retry on connection/operation failure. I'm closing this in favor of the elastic2-doc-manager issue that tracks retrying operations on failure: https://github.com/mongodb-labs/elastic2-doc-manager/issues/18

**Closed by ShaneHarvey** 2017-01-24 20:45 UTC

**Comment by BlueRayONE** [comment] 2017-01-30 08:47
Alright. I'll follow this issue. Thanks!
The reason for the long responsetime of ES was simple: diskspace was full, ooops ;) won't happen again.
