### ISSUE TITLE
the oplog-manager thread exits if it loses connection to the mongodb

### ISSUE THREAD

**Issue by Jinshui** [mongodb-labs/mongo-connector#365] opened 2015-12-04 04:55 UTC
I recently had a test to see what happen if I restart mongodb when mongo-connector is connected to the mondb, and found that restarting mongodb will cause the mongo-connector stop working, the root cause is the oplog-thread won't retry it there is problem with the connection. The following is the error cause I caught:
```
2015-12-04 01:27:09,735 [ERROR] mongo_connector.oplog_manager:310 - Cursor closed due to an exception. Will attempt to reconnect.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 185, in run
    for n, entry in enumerate(cursor):
  File "/usr/lib64/python2.6/site-packages/pymongo/cursor.py", line 1149, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib64/python2.6/site-packages/pymongo/cursor.py", line 1098, in _refresh
    limit, self.__id))
  File "/usr/lib64/python2.6/site-packages/pymongo/cursor.py", line 996, in __send_message
    res = client._send_message_with_response(message, **kwargs)
  File "/usr/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 1366, in _send_message_with_response
    raise AutoReconnect(str(e))
AutoReconnect: connection closed
2015-12-04 01:27:09,741 [ERROR] mongo_connector.util:87 - Fatal Exception
```

It says it will attempt to reconnect, but before that, it first call the function update_checkpoint() which also throws an error if it cannot connect to the mongodb,  and finally lead the thread to exit:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 320, in run
    self.update_checkpoint()
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 645, in update_checkpoint
    oplog_dict[str(self.oplog)] = self.checkpoint
  File "/usr/lib64/python2.6/site-packages/pymongo/collection.py", line 180, in __repr__
    return "Collection(%r, %r)" % (self.__database, self.__name)
  File "/usr/lib64/python2.6/site-packages/pymongo/database.py", line 207, in __repr__
    return "Database(%r, %r)" % (self.__connection, self.__name)
  File "/usr/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 1463, in __repr__
    return "MongoClient(%r, %r)" % self.address
TypeError: not enough arguments for format string
```

Please fix this.

**Comment by aherlihy** [comment] 2016-02-17 13:11
Hello!

What version are you working with? We just released 2.2, if you can please give it a try with the new version and report any errors. Thank you!

**Comment by oxymor0n** [comment] 2016-04-26 15:45
I'm encountering the same error, with `mongo-connector` 2.3 and `pymongo` 2.9.1

**Comment by oxymor0n** [comment] 2016-04-26 15:57
It looks like `pymongo` expect the MongoClient object's `self.address` property to contain a tuple, but it actually contains something else (very likely a str but I haven't confirmed). Without diving into the specifics of the `pymongo` driver, I think the easiest solution to this would be to change the `update_checkpoint` function so that it does not rely on the string representation of the `self.oplog` collection in the `oplog_manager`, but to use the `full_name` property instead.

**Comment by behackett** [comment] 2016-04-26 16:09
https://jira.mongodb.org/browse/PYTHON-1088

mongo-connector can use PyMongo 3.x. Unless you have a really good reason for continuing to use 2.9, I suggest you upgrade.

**Comment by oxymor0n** [comment] 2016-04-26 16:25
I see, thanks

**Comment by behackett** [comment] 2016-04-26 16:29
I'm closing this issue since the bug is in PyMongo 2.9.x, not mongo-connector. The workaround is to upgrade to the latest version of PyMongo. mongo-connector fully supports PyMongo 3.x, and PyMongo 3.x is much more resilient in the face of replica set failures and reconfigurations.

**Closed by behackett** 2016-04-26 16:29 UTC
Labels: waiting for input
