### ISSUE TITLE
mongo-connector switches between head and tail of oplog

### ISSUE THREAD

**Issue by rodriguezsergio** [mongodb-labs/mongo-connector#556] opened 2016-10-21 19:02 UTC
edit:
If I wanted to "hack" the oplog.timestamp file with a time much closer to the present, would that be enough to fast forward the tailing process? I'm reading the code now to see how this all works, but hopefully someone can answer me sooner than I can parse this.
/edit

So I've been evaluating mongo-connector for internal use at work and the first few times I was refreshing Kibana expecting to see documents from the last hour, but it wasn't until I set the time range to the last 90 days did I see documents being inserted at August 20(!!!). Now this would not be a problem if the size of the data set that I was importing wasn't big, but unfortunately it would take far too long to catch up to the present.

Glossing over the issues here, I didn't see many complaints so I dropped the index and tried again several times. It wasn't until the 4th or 5th time that it finally decided to use the tail of the oplog as opposed to the head.

This is quite frustrating because I was planning on using this in production in the not too distant future, but I would consider this issue a blocker. I'm running mongo-connector (2.4.1) and I've pasted my config below.

```json
{
    "noDump": true,
    "verbosity": 3,
    "timezoneAware": true,
    "namespaces": {
      "include": ["$DB.$COLLECTION"]
    }
}
```

The logs seem to contradict the behavior I'm seeing in Kibana.
```
$ grep 'oplog entry has' mongo-connector.log
2016-10-21 11:56:58,870 [DEBUG] mongo_connector.oplog_manager:659 - OplogThread: Newest oplog entry has timestamp 1477065418.
```
That timestamp corresponds to today, specifically this time:
GMT: Fri, 21 Oct 2016 15:56:58 GMT

![screen shot 2016-10-21 at 2 02 03 pm](https://cloud.githubusercontent.com/assets/2318521/19608443/6eeec900-979f-11e6-809d-05e200db8dfd.png)

**Comment by ShaneHarvey** [comment] 2016-10-21 22:18
`"noDump": true` means that mongo-connector will not copy over existing collections and instead will start replicating oplog entries from the  *begining* of the oplog. That is the intended behavior. It does look like we start reading the oplog from the oldest entry but then checkpoint the newest entry, which should be fixed. See here https://github.com/mongodb-labs/mongo-connector/blob/2eff317/mongo_connector/oplog_manager.py#L850-L853

What you want is a way to tell mongo-connector to start tailing the oplog from the *end* of the oplog, correct? What if we add an option to start from a specific oplog entry timestamp?

**Comment by ShaneHarvey** [comment] 2016-10-21 22:55
In the mean time you can manually create your own oplog progress file.

```python
import bson
import json
import sys
import pymongo


def bson_ts_to_long(timestamp):
    """Convert BSON timestamp into integer.

    Conversion rule is based from the specs
    (http://bsonspec.org/#/specification).
    """
    return ((timestamp.time << 32) + timestamp.inc)


def write_oplog_progress(progress_path, progress_dict):
    """ Writes oplog progress to file provided by user
    """
    items = [[name, bson_ts_to_long(progress_dict[name])]
             for name in progress_dict]
    if not items:
        return

    # for each of the threads write to file
    with open(progress_path, 'w') as dest:
        if len(items) == 1:
            # Write 1-dimensional array, as in previous versions.
            json_str = json.dumps(items[0])
        else:
            # Write a 2d array to support sharded clusters.
            json_str = json.dumps(items)
        try:
            dest.write(json_str)
        except IOError:
            exit('Failed to write to file!')

def get_newest_oplog_timestamp(client):
    """Return the timestamp of the newest entry in the oplog.
    """
    curr = client.local.oplog.rs.find(
        {'op': {'$ne': 'n'}}).sort('$natural', pymongo.DESCENDING).limit(-1)

    try:
        ts = next(curr)['ts']
    except StopIteration:
        exit("oplog is empty.")

    return ts


if __name__ == '__main__':
    if len(sys.argv) != 4:
        exit('usage: ./write_oplog_progress.py oplog_timestamp_file replica_set_name host_or_mongodb_uri')
    progress_path = sys.argv[1]
    client = pymongo.MongoClient(sys.argv[3])
    progress_dict = {sys.argv[2]: get_newest_oplog_timestamp(client)}
    write_oplog_progress(progress_path, progress_dict)
    print('wrote lastest oplog entry to: ' + progress_path)
```

Example Usage:
```bash
$ python write_oplog_progress.py ./new_oplog.timestamp 425f5bba-7834-4d9e-9799-382d63f361b9 localhost:27017
wrote lastest oplog entry to: ./new_oplog.timestamp
$ cat ./new_oplog.timestamp
["425f5bba-7834-4d9e-9799-382d63f361b9", 6344054334170333186]%
$ mongo-connector <your options> --oplog-ts ./new_oplog.timestamp
```

**Comment by rodriguezsergio** [comment] 2016-10-24 16:44
Yeah, I misread the docs. I glossed over the first part of this sentence
>It synchronizes data in MongoDB to the target then tails the MongoDB oplog, keeping up with operations in MongoDB in real-time.

and just saw `it tails the MongoDB oplog` and thought that was the default behavior whether noDump is true or false.

**Comment by ShaneHarvey** [comment] 2016-10-28 22:32
Closing this as a duplicate of #305.

**Closed by ShaneHarvey** 2016-10-28 22:32 UTC
